name = "spectra-whois-tcp-proxy"
main = "worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "spectra-whois-tcp-proxy"

[env.development]
name = "spectra-whois-tcp-proxy-dev"

# Enable TCP connections
[env.production.durable_objects]
bindings = []

[env.development.durable_objects]
bindings = []

# Optional: Add analytics
[env.production.analytics_engine_datasets]

[env.development.analytics_engine_datasets]